### ISSUE TITLE
非常感谢，不更新了吗

### ISSUE THREAD

**Issue by hawind** [larisgo/laravel-echo-server#1]

**Comment by zishang520** [comment]
@hawind  要更新，在重新一个可用的socketio，目前现有dwsocketio包兼容性不怎么好

**Comment by hawind** [comment]
很喜欢这个，感觉很强大socketio似乎在go里没有啥好用的，感觉半死不活

**Comment by zishang520** [comment]
> 很喜欢这个，感觉很强大socketio似乎在go里没有啥好用的，感觉半死不活

看了好多个socketio都没几个更新的，因为socketio的包问题我也搁浅许久了

**Comment by zishang520** [comment]
您好，新的代码已更新（待测试)
